version: "3"

services:
  mysql:
    image: mysql:5.6
    container_name: bibleapp-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=bibleapp
      - MYSQL_USER=bibleapp
      - MYSQL_PASSWORD=bibleapp
      - MYSQL_ROOT_PASSWORD=bibleapp
    volumes:
      - ./server/logs/mysql:/var/log/mysql
      - ./server/data/mysql:/var/lib/mysql
      - ./server/config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf

  flyway:
    container_name: bibleapp-flyway
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:mysql://mysql/bibleapp -schemas=bibleapp -user=bibleapp -password=bibleapp -connectRetries=60 migrate
    volumes:
      - ./server/migrations:/flyway/sql
    links:
      - mysql
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bibleapp-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8888:80
    volumes:
      - /sessions
      - ./server/config/phpmyadmin/php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    links:
      - mysql
    depends_on:
      - mysql

  webserver:
    build:
      context: ./server/bin/php7
    container_name: bibleapp-webserver
    restart: always
    ports:
      - 8000:80
      # - 443:443
    volumes:
      - .:/var/www/html
      - ./server/config/php/php.ini:/usr/local/etc/php/php.ini
      - ./server/config/vhosts:/etc/apache2/sites-enabled
      - ./server/logs/apache2:/var/log/apache2
    links:
      - mysql
    depends_on:
      - flyway
