version: '3.3'
services:
  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    container_name: pablo-24-7-node
    restart: always
    # environment:
    #   - VAR=value
    ports:
      - 81:5000
    # volumes:
    #   - ./.temp/postgres-data:/var/lib/postgresql/data
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    container_name: pablo-24-7-nginx
    restart: always
    ports:
    - 80:80
    depends_on:
    - node
